package gateway

// DefaultFeatureCatalog는 웹 패널/Discord/Slack adapter가 사용할 수 있는 gateway 기능 표면을 알려줘요.
func DefaultFeatureCatalog() []FeatureDTO {
	return []FeatureDTO{
		{Name: "operations", Status: "implemented", Description: "배포 health/readiness probe와 API bootstrap discovery를 제공해요.", Endpoints: []string{"GET /healthz", "GET /readyz", "GET /api/v1"}},
		{Name: "openapi", Status: "implemented", Description: "외부 adapter와 SDK generator가 현재 gateway OpenAPI 계약을 직접 내려받을 수 있어요.", Endpoints: []string{"GET /api/v1", "GET /api/v1/openapi.yaml"}},
		{Name: "sessions", Status: "implemented", Description: "session 생성, 목록, 상세, export/import, turn/transcript 조회, compact, fork를 제공해요.", Endpoints: []string{"GET /api/v1/sessions", "POST /api/v1/sessions", "POST /api/v1/sessions/import", "GET /api/v1/sessions/{session_id}", "GET /api/v1/sessions/{session_id}/export", "GET /api/v1/sessions/{session_id}/turns", "GET /api/v1/sessions/{session_id}/turns/{turn_id}", "GET /api/v1/sessions/{session_id}/transcript", "POST /api/v1/sessions/{session_id}/compact", "POST /api/v1/sessions/{session_id}/fork"}},
		{Name: "session_events", Status: "implemented", Description: "session event JSON replay와 SSE replay를 제공해요.", Endpoints: []string{"GET /api/v1/sessions/{session_id}/events"}},
		{Name: "todos", Status: "implemented", Description: "agent todo 상태를 외부 status UI에서 읽고 수정할 수 있어요.", Endpoints: []string{"GET /api/v1/sessions/{session_id}/todos", "PUT /api/v1/sessions/{session_id}/todos", "POST /api/v1/sessions/{session_id}/todos", "DELETE /api/v1/sessions/{session_id}/todos/{todo_id}"}},
		{Name: "checkpoints", Status: "implemented", Description: "session checkpoint를 저장하고 replay/복구용 snapshot payload를 조회할 수 있어요.", Endpoints: []string{"GET /api/v1/sessions/{session_id}/checkpoints", "POST /api/v1/sessions/{session_id}/checkpoints", "GET /api/v1/sessions/{session_id}/checkpoints/{checkpoint_id}"}},
		{Name: "background_runs", Status: "implemented", Description: "run을 즉시 접수하고 background 상태 조회, 취소, live SSE event, 실행 전 preview, run/request 단위 transcript를 제공해요.", Endpoints: []string{"GET /api/v1/runs", "POST /api/v1/runs", "POST /api/v1/runs/preview", "POST /api/v1/runs/validate", "GET /api/v1/runs/{run_id}", "GET /api/v1/runs/{run_id}/events", "GET /api/v1/runs/{run_id}/transcript", "POST /api/v1/runs/{run_id}/cancel", "POST /api/v1/runs/{run_id}/retry", "GET /api/v1/requests/{request_id}/runs", "GET /api/v1/requests/{request_id}/events", "GET /api/v1/requests/{request_id}/transcript"}},
		{Name: "providers", Status: "implemented", Description: "provider 목록, alias, model, auth, 변환 profile discovery와 provider 단독 preflight/test를 제공해요.", Endpoints: []string{"GET /api/v1/providers", "GET /api/v1/providers/{provider}", "POST /api/v1/providers/{provider}/test"}},
		{Name: "models", Status: "implemented", Description: "외부 adapter가 provider별 모델 선택 UI를 만들 수 있게 model catalog를 제공해요.", Endpoints: []string{"GET /api/v1/models"}},
		{Name: "stats", Status: "implemented", Description: "dashboard adapter가 session/run/resource 상태 카운트를 한 번에 볼 수 있어요.", Endpoints: []string{"GET /api/v1/stats"}},
		{Name: "diagnostics", Status: "implemented", Description: "배포 상태, store ping, runtime wiring, provider auth, default MCP 상태를 한 번에 점검해요.", Endpoints: []string{"GET /api/v1/diagnostics"}},
		{Name: "prompts", Status: "implemented", Description: "system/session/todo prompt 템플릿 목록, 원문, 렌더링 preview를 제공해요.", Endpoints: []string{"GET /api/v1/prompts", "GET /api/v1/prompts/{template_name}", "POST /api/v1/prompts/{template_name}/render"}},
		{Name: "mcp", Status: "implemented", Description: "MCP server manifest를 API와 SQLite에 저장하고 provider 연결 설정으로 재사용할 수 있어요.", Endpoints: []string{"GET /api/v1/mcp/servers", "POST /api/v1/mcp/servers", "GET /api/v1/mcp/servers/{resource_id}", "PUT /api/v1/mcp/servers/{resource_id}", "DELETE /api/v1/mcp/servers/{resource_id}", "GET /api/v1/mcp/servers/{resource_id}/tools", "GET /api/v1/mcp/servers/{resource_id}/resources", "GET /api/v1/mcp/servers/{resource_id}/resources/read", "GET /api/v1/mcp/servers/{resource_id}/prompts", "POST /api/v1/mcp/servers/{resource_id}/prompts/{prompt_name}/get", "POST /api/v1/mcp/servers/{resource_id}/tools/{tool_name}/call"}},
		{Name: "skills", Status: "implemented", Description: "Skill manifest를 API와 SQLite에 저장하고 provider skill directory/prompt 설정으로 재사용할 수 있어요.", Endpoints: []string{"GET /api/v1/skills", "POST /api/v1/skills", "GET /api/v1/skills/{resource_id}", "PUT /api/v1/skills/{resource_id}", "DELETE /api/v1/skills/{resource_id}", "GET /api/v1/skills/{resource_id}/preview"}},
		{Name: "subagents", Status: "implemented", Description: "Subagent manifest를 API와 SQLite에 저장하고 custom agent 설정으로 재사용할 수 있어요.", Endpoints: []string{"GET /api/v1/subagents", "POST /api/v1/subagents", "GET /api/v1/subagents/{resource_id}", "PUT /api/v1/subagents/{resource_id}", "DELETE /api/v1/subagents/{resource_id}", "GET /api/v1/subagents/{resource_id}/preview"}},
		{Name: "lsp", Status: "implemented", Description: "Go source symbol index, definition/reference, rename/format preview, diagnostics, hover를 LSP-style API로 조회할 수 있어요.", Endpoints: []string{"GET /api/v1/lsp/symbols", "GET /api/v1/lsp/document-symbols", "GET /api/v1/lsp/definitions", "GET /api/v1/lsp/references", "GET /api/v1/lsp/rename-preview", "GET /api/v1/lsp/format-preview", "GET /api/v1/lsp/diagnostics", "GET /api/v1/lsp/hover"}},
		{Name: "tools", Status: "implemented", Description: "file/shell/web/codeintel 표준 tool 목록, 상세, 직접 실행 API를 제공해요. 권한 프롬프트 없이 바로 실행해요.", Endpoints: []string{"GET /api/v1/tools", "GET /api/v1/tools/{tool}", "POST /api/v1/tools/call"}},
		{Name: "files", Status: "implemented", Description: "웹 패널용 파일 목록, 읽기, 쓰기, patch, glob, grep API를 제공해요. 권한 프롬프트 없이 바로 실행해요.", Endpoints: []string{"GET /api/v1/files", "GET /api/v1/files/content", "PUT /api/v1/files/content", "POST /api/v1/files/patch", "GET /api/v1/files/glob", "GET /api/v1/files/grep"}},
		{Name: "git", Status: "implemented", Description: "웹 패널이 변경사항을 렌더링할 수 있게 git status, diff, log를 제공해요.", Endpoints: []string{"GET /api/v1/git/status", "GET /api/v1/git/diff", "GET /api/v1/git/log"}},
	}
}

// DefaultProviderCapabilityCatalog는 provider capability map에 쓰는 key의 의미를 한 곳에서 설명해요.
// provider별 capability map은 true 값만 노출해서 작게 유지하고, 빠진 key의 의미는 이 catalog로 해석해요.
func DefaultProviderCapabilityCatalog() []ProviderCapabilityKeyDTO {
	return []ProviderCapabilityKeyDTO{
		{Name: "tools", Description: "표준 function/custom/built-in tool call을 provider 요청에 포함할 수 있어요."},
		{Name: "custom_tools", Description: "자유 형식 custom tool 호출이나 grammar 기반 tool을 다룰 수 있어요."},
		{Name: "reasoning", Description: "thinking/reasoning 설정이나 reasoning item을 보존할 수 있어요."},
		{Name: "reasoning_summaries", Description: "reasoning summary 요청과 응답 summary를 다룰 수 있어요."},
		{Name: "structured_output", Description: "JSON schema 같은 structured output 형식을 요청할 수 있어요."},
		{Name: "streaming", Description: "stream source를 통해 event 단위 응답을 받을 수 있어요."},
		{Name: "tool_choice", Description: "auto/none/required/특정 tool 같은 tool choice를 전달할 수 있어요."},
		{Name: "parallel_tool_calls", Description: "provider가 병렬 tool call을 생성하거나 허용하는 힌트를 이해해요."},
		{Name: "prompt_refs", Description: "provider prompt 저장소 ID/version/variables를 요청에 실을 수 있어요."},
		{Name: "previous_response_id", Description: "Responses API 계열의 previous_response_id 같은 연속 응답 ID를 이어갈 수 있어요."},
		{Name: "mcp", Description: "MCP server/tool 설정을 provider source나 built-in tool로 연결할 수 있어요."},
		{Name: "skills", Description: "Skill directory나 skill prompt context를 provider/session 설정에 반영할 수 있어요."},
		{Name: "custom_agents", Description: "Subagent/custom agent manifest를 provider/session 설정에 반영할 수 있어요."},
		{Name: "a2a", Description: "Agent-to-Agent endpoint나 task 프로토콜을 provider 기능으로 사용할 수 있어요."},
		{Name: "routing", Description: "계정/모델/source routing을 provider gateway 쪽에서 수행할 수 있어요."},
	}
}

// DefaultProviderPipelineCatalog는 모든 provider가 맞춰야 하는 source 확장 흐름을 설명해요.
// 새 API를 붙일 때는 이 단계 중 converter와 caller만 추가하고 agent/runtime/gateway 타입은 그대로 유지해요.
func DefaultProviderPipelineCatalog() []ProviderPipelineStageDTO {
	return []ProviderPipelineStageDTO{
		{Name: "request", Input: "gateway.RunStartRequest 또는 runtime.RunOptions", Output: "llm.Request", Description: "웹 패널, Discord, CLI 요청을 provider-neutral 표준 요청으로 조립해요."},
		{Name: "convert_request", Input: "llm.Request", Output: "llm.ProviderRequest", Description: "RequestConverter가 OpenAI Responses payload, Copilot prompt, Codex exec payload 같은 source별 요청으로 바꿔요."},
		{Name: "api_call", Input: "llm.ProviderRequest", Output: "llm.ProviderResult 또는 llm.EventStream", Description: "ProviderCaller/ProviderStreamCaller가 HTTP API, SDK session, CLI subprocess, in-memory source를 실제 호출해요."},
		{Name: "convert_response", Input: "llm.ProviderResult", Output: "llm.Response", Description: "ResponseConverter가 provider raw 응답을 표준 text, tool call, reasoning item, usage로 되돌려요."},
		{Name: "agent_loop", Input: "llm.Response", Output: "tool result 또는 final response", Description: "agent가 tool call을 즉시 실행하고 tool output을 다음 llm.Request에 누적해요."},
		{Name: "persist_replay", Input: "runtime trace와 run event", Output: "SQLite session/run/event record", Description: "gateway가 같은 결과를 polling, SSE, retry, transcript UI에서 재사용해요."},
	}
}

// APIIndexLinks는 adapter bootstrap에 필요한 대표 endpoint link를 한 곳에서 관리해요.
func APIIndexLinks() map[string]string {
	return map[string]string{
		"health":                    "/healthz",
		"ready":                     "/readyz",
		"api_index":                 "/api/v1",
		"openapi":                   "/api/v1/openapi.yaml",
		"version":                   "/api/v1/version",
		"capabilities":              "/api/v1/capabilities",
		"diagnostics":               "/api/v1/diagnostics",
		"providers":                 "/api/v1/providers",
		"provider_detail":           "/api/v1/providers/{provider}",
		"provider_test":             "/api/v1/providers/{provider}/test",
		"models":                    "/api/v1/models",
		"stats":                     "/api/v1/stats",
		"sessions":                  "/api/v1/sessions",
		"session_create":            "/api/v1/sessions",
		"session_import":            "/api/v1/sessions/import",
		"session_detail":            "/api/v1/sessions/{session_id}",
		"session_export":            "/api/v1/sessions/{session_id}/export",
		"session_events":            "/api/v1/sessions/{session_id}/events",
		"session_transcript":        "/api/v1/sessions/{session_id}/transcript",
		"session_turns":             "/api/v1/sessions/{session_id}/turns",
		"session_turn_detail":       "/api/v1/sessions/{session_id}/turns/{turn_id}",
		"session_compact":           "/api/v1/sessions/{session_id}/compact",
		"session_fork":              "/api/v1/sessions/{session_id}/fork",
		"session_todos":             "/api/v1/sessions/{session_id}/todos",
		"session_todos_replace":     "/api/v1/sessions/{session_id}/todos",
		"session_todo_upsert":       "/api/v1/sessions/{session_id}/todos",
		"session_todo_delete":       "/api/v1/sessions/{session_id}/todos/{todo_id}",
		"session_checkpoints":       "/api/v1/sessions/{session_id}/checkpoints",
		"session_checkpoint_create": "/api/v1/sessions/{session_id}/checkpoints",
		"session_checkpoint_detail": "/api/v1/sessions/{session_id}/checkpoints/{checkpoint_id}",
		"runs":                      "/api/v1/runs",
		"run_start":                 "/api/v1/runs",
		"run_preview":               "/api/v1/runs/preview",
		"run_validate":              "/api/v1/runs/validate",
		"run_detail":                "/api/v1/runs/{run_id}",
		"run_events":                "/api/v1/runs/{run_id}/events",
		"run_transcript":            "/api/v1/runs/{run_id}/transcript",
		"run_retry":                 "/api/v1/runs/{run_id}/retry",
		"run_cancel":                "/api/v1/runs/{run_id}/cancel",
		"request_runs":              "/api/v1/requests/{request_id}/runs",
		"request_events":            "/api/v1/requests/{request_id}/events",
		"request_transcript":        "/api/v1/requests/{request_id}/transcript",
		"tools":                     "/api/v1/tools",
		"tool_detail":               "/api/v1/tools/{tool}",
		"tool_call":                 "/api/v1/tools/call",
		"files":                     "/api/v1/files",
		"file_content":              "/api/v1/files/content",
		"file_write":                "/api/v1/files/content",
		"file_patch":                "/api/v1/files/patch",
		"file_glob":                 "/api/v1/files/glob",
		"file_grep":                 "/api/v1/files/grep",
		"git":                       "/api/v1/git/status",
		"git_status":                "/api/v1/git/status",
		"git_diff":                  "/api/v1/git/diff",
		"git_log":                   "/api/v1/git/log",
		"mcp_servers":               "/api/v1/mcp/servers",
		"mcp_server_create":         "/api/v1/mcp/servers",
		"mcp_server_detail":         "/api/v1/mcp/servers/{resource_id}",
		"mcp_server_update":         "/api/v1/mcp/servers/{resource_id}",
		"mcp_server_delete":         "/api/v1/mcp/servers/{resource_id}",
		"mcp_server_tools":          "/api/v1/mcp/servers/{resource_id}/tools",
		"mcp_server_resources":      "/api/v1/mcp/servers/{resource_id}/resources",
		"mcp_resource_read":         "/api/v1/mcp/servers/{resource_id}/resources/read",
		"mcp_server_prompts":        "/api/v1/mcp/servers/{resource_id}/prompts",
		"mcp_prompt_get":            "/api/v1/mcp/servers/{resource_id}/prompts/{prompt_name}/get",
		"mcp_tool_call":             "/api/v1/mcp/servers/{resource_id}/tools/{tool_name}/call",
		"skills":                    "/api/v1/skills",
		"skill_create":              "/api/v1/skills",
		"skill_detail":              "/api/v1/skills/{resource_id}",
		"skill_update":              "/api/v1/skills/{resource_id}",
		"skill_delete":              "/api/v1/skills/{resource_id}",
		"skill_preview":             "/api/v1/skills/{resource_id}/preview",
		"subagents":                 "/api/v1/subagents",
		"subagent_create":           "/api/v1/subagents",
		"subagent_detail":           "/api/v1/subagents/{resource_id}",
		"subagent_update":           "/api/v1/subagents/{resource_id}",
		"subagent_delete":           "/api/v1/subagents/{resource_id}",
		"subagent_preview":          "/api/v1/subagents/{resource_id}/preview",
		"lsp_symbols":               "/api/v1/lsp/symbols",
		"lsp_document_symbols":      "/api/v1/lsp/document-symbols",
		"lsp_definitions":           "/api/v1/lsp/definitions",
		"lsp_references":            "/api/v1/lsp/references",
		"lsp_rename_preview":        "/api/v1/lsp/rename-preview",
		"lsp_format_preview":        "/api/v1/lsp/format-preview",
		"lsp_diagnostics":           "/api/v1/lsp/diagnostics",
		"lsp_hover":                 "/api/v1/lsp/hover",
		"prompts":                   "/api/v1/prompts",
		"prompt_detail":             "/api/v1/prompts/{template_name}",
		"prompt_render":             "/api/v1/prompts/{template_name}/render",
	}
}
